### ISSUE TITLE
Facebook error

### ISSUE THREAD

**Issue by kapsona** [flyandi/react-native-openanything#1]
canOpenURL: failed for URL: "fb://profile/MY_FACEBOOK_ID" - error: "This app is not allowed to query for scheme fb"

Also on another subject are there any plans to add linkedin and instagram links handling?

**Comment by flyandi** [comment]
You might have to add `LSApplicationQueriesSchemes` with the value `Facebook` to it.

I will see what I can do regarding LinkedIn and Instagram.

**Comment by flyandi** [comment]
Instagram support added in 0.0.4

**Comment by flyandi** [comment]
I updated the readme to reflect the above issue.


Target | Query Scheme
-- | --
Facebook | fb
Instagram | instagram
Twitter | twitter
LinkedIn | linkedin
WhatsApp | whatsapp
