### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by gdierksmeier** [flyandi/react-native-openanything#2]
Can you please add an example how to open a PDF...
Thanks

**Comment by alaboudi** [comment]
PDF please

**Comment by flyandi** [comment]
You could use `intent://`  or let me add this as a feature request.

**Comment by WesleyFaveri** [comment]
+1

**Comment by WesleyFaveri** [comment]
I made a PR to finish PDF support #6

**Comment by flyandi** [comment]
Accepted.

**Comment by WesleyFaveri** [comment]
@flyandi can you publish new version?

**Comment by flyandi** [comment]
Done. Thanks for reminding me - I totally forgot :)

0.0.5 pushed.

**Comment by WesleyFaveri** [comment]
i think you missed merge pdf pr #6  @flyandi
