### ISSUE TITLE
Open inbox email

### ISSUE THREAD

**Issue by fachrinfl** [flyandi/react-native-openanything#4]
i only want to open the email inbox app, how can i do that ?

**Comment by flyandi** [comment]
The internal app email inbox or just focus the email app?

**Comment by fachrinfl** [comment]
@flyandi i just want to open app gmail

**Comment by flyandi** [comment]
So just to be clear - you don't want to actually start a new email but just focus the email client?

You would have to start manually the gmail app, I think all `intents` are centered around actually sending an email via the native app - not just focusing it.

**Comment by flyandi** [comment]
Here you go - you can use the following component to achieve this: https://www.npmjs.com/package/react-native-mail

**Comment by fachrinfl** [comment]
Thanks for the advice @flyandi

**Comment by flyandi** [comment]
U welcome.
